version: '2'

services:
    postgresql:
        image: postgres
        container_name: postgres-stubb
        ports:
            - "5432:5432"
        environment:         
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_HOST_AUTH_METHOD=trust
